blueprint:
  name: LD2450 Zone Creation
  description: >
    Create a zone for the LD2450 radar sensor (Apollo MTR-1/R-PRO-1) by collecting X/Y position data for a target over a set duration. Automatically handles single target mode, outlier filtering, and provides a summary of the created zone.
  domain: automation
  input:
    zone_x1_entity:
      name: Zone X1 Number Entity
      description: Select the X1 number entity for the zone you want to set.
      selector:
        entity:
          domain: number
    duration:
      name: Collection Duration (seconds)
      description: How long to collect X/Y data for zone creation.
      default: 15
      selector:
        number:
          min: 10
          max: 300
          step: 1
    padding:
      name: Padding (mm)
      description: |
        Padding to add to the zone boundaries (in mm). There are approximately 304.8 mm in a foot.
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          step: 10

mode: single

trigger:
  - platform: state
    entity_id: input_button.ld2450_zone_create
  - platform: event
    event_type: ld2450_zone_create

variables:
  zone_x1_entity: !input zone_x1_entity
  device_base_name: "{{ zone_x1_entity.split('_zone_')[0].split('number.')[1] }}"
  zone: "{{ zone_x1_entity.split('_zone_')[1].split('_')[0] }}"
  x_entity: "sensor.{{ device_base_name }}_target_1_x"
  y_entity: "sensor.{{ device_base_name }}_target_1_y"
  zone_x1: "number.{{ device_base_name }}_zone_{{ zone }}_x1"
  zone_x2: "number.{{ device_base_name }}_zone_{{ zone }}_x2"
  zone_y1: "number.{{ device_base_name }}_zone_{{ zone }}_y1"
  zone_y2: "number.{{ device_base_name }}_zone_{{ zone }}_y2"
  multi_switch: "switch.{{ device_base_name }}_multi_target_tracking"
  duration: !input duration
  padding: !input padding

action:
  - alias: "Store current multi-target state and switch to single target mode (if switch exists)"
    choose:
      - conditions:
          - condition: template
            value_template: "{{ states(multi_switch) is not none }}"
        sequence:
          - variables:
              prev_multi_state: "{{ states(multi_switch) }}"
          - service: switch.turn_off
            target:
              entity_id: "{{ multi_switch }}"
  - alias: "Detect units and convert all values to mm for calculation"
    variables:
      x_uom: "{{ state_attr(x_entity, 'unit_of_measurement') or 'mm' }}"
      y_uom: "{{ state_attr(y_entity, 'unit_of_measurement') or 'mm' }}"
      zone_x1_uom: "{{ state_attr(zone_x1, 'unit_of_measurement') or 'mm' }}"
      zone_x2_uom: "{{ state_attr(zone_x2, 'unit_of_measurement') or 'mm' }}"
      zone_y1_uom: "{{ state_attr(zone_y1, 'unit_of_measurement') or 'mm' }}"
      zone_y2_uom: "{{ state_attr(zone_y2, 'unit_of_measurement') or 'mm' }}"
      uom_to_mm: {
        'mm': 1,
        'cm': 10,
        'm': 1000,
        'in': 25.4,
        'ft': 304.8,
        'yd': 914.4
      }
  - alias: "Initialize data collection"
    variables:
      x_values: []
      y_values: []
      start_time: "{{ now().timestamp() }}"
  - alias: "Collect X/Y data for duration (convert to mm)"
    repeat:
      while:
        - condition: template
          value_template: "{{ (now().timestamp() - start_time) < duration }}"
      sequence:
        - variables:
            x_raw: "{{ states(x_entity) | float(0) }}"
            y_raw: "{{ states(y_entity) | float(0) }}"
            x: "{{ x_raw * uom_to_mm[x_uom] }}"
            y: "{{ y_raw * uom_to_mm[y_uom] }}"
        - if:
            - condition: template
              value_template: "{{ x is number and y is number and not (x == 0 and y == 0) }}"
          then:
            - variables:
                x_values: "{{ x_values + [x] }}"
                y_values: "{{ y_values + [y] }}"
        - delay: 1
  - alias: "Calculate min/max and apply padding (in mm)"
    variables:
      min_x: "{{ (x_values | length > 0 and (x_values | min) or 0) - padding }}"
      max_x: "{{ (x_values | length > 0 and (x_values | max) or 0) + padding }}"
      min_y: "{{ (y_values | length > 0 and (y_values | min) or 0) - padding }}"
      max_y: "{{ (y_values | length > 0 and (y_values | max) or 0) + padding }}"
  - alias: "Clamp values to valid range"
    variables:
      min_x: "{{ [[min_x, -4860.0] | max, 4860.0] | min }}"
      max_x: "{{ [[max_x, -4860.0] | max, 4860.0] | min }}"
      min_y: "{{ [[min_y, 0] | max, 7560.0] | min }}"
      max_y: "{{ [[max_y, 0] | max, 7560.0] | min }}"
  - alias: "Convert results from mm to each zone entity's uom"
    variables:
      min_x_conv: "{{ min_x / uom_to_mm[zone_x1_uom] }}"
      max_x_conv: "{{ max_x / uom_to_mm[zone_x2_uom] }}"
      min_y_conv: "{{ min_y / uom_to_mm[zone_y1_uom] }}"
      max_y_conv: "{{ max_y / uom_to_mm[zone_y2_uom] }}"
  - alias: "Set zone coordinates"
    sequence:
      - service: number.set_value
        data:
          entity_id: "{{ zone_x1 }}"
          value: "{{ min_x_conv }}"
      - service: number.set_value
        data:
          entity_id: "{{ zone_x2 }}"
          value: "{{ max_x_conv }}"
      - service: number.set_value
        data:
          entity_id: "{{ zone_y1 }}"
          value: "{{ min_y_conv }}"
      - service: number.set_value
        data:
          entity_id: "{{ zone_y2 }}"
          value: "{{ max_y_conv }}"
  - alias: "Restore previous multi-target state (if switch exists)"
    choose:
      - conditions:
          - condition: template
            value_template: "{{ states(multi_switch) is not none }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ multi_switch }}"
  - alias: "Send summary notification"
    service: persistent_notification.create
    data:
      title: "LD2450 {{ device_base_name }} Zone {{ zone }} Created"
      message: |
        X1: {{ min_x_conv }} {{ zone_x1_uom }}
        X2: {{ max_x_conv }} {{ zone_x2_uom }}
        Y1: {{ min_y_conv }} {{ zone_y1_uom }}
        Y2: {{ max_y_conv }} {{ zone_y2_uom }}
        Padding: {{ padding }} mm
        Duration: {{ duration }} seconds
